<!DOCTYPE html>
<html>
<head>
    <script>
        /*JavaScript 测试和捕捉

        try 语句允许我们定义在执行时进行错误测试的代码块。

        catch 语句允许我们定义当 try 代码块发生错误时，所执行的代码块。

        JavaScript 语句 try 和 catch 是成对出现的。

        语法
        try
        {  //在这里运行代码
        }
        catch(err)
        {  //在这里处理错误
        }
        */
        var txt="";
        function message()
        {
            try
            {  adddlert("Welcome guest!");
            }
            catch(err)
            {
                txt="There was an error on this page.\n\n";
                txt+="Error description: " + err.message + "\n\n";
                txt+="Click OK to continue.\n\n";
                alert(txt);
            }
        }

    </script>

</head>

<body>
<input type="button" value="View message" onclick="message()">
<script>
    /*
    * Throw 语句

     throw 语句允许我们创建自定义错误。

     正确的技术术语是：创建或抛出异常（exception）。

     如果把 throw 与 try 和 catch 一起使用，那么您能够控制程序流，并生成自定义的错误消息。

     语法
     throw exception

     异常可以是 JavaScript 字符串、数字、逻辑值或对象。
     实例

     本例检测输入变量的值。如果值是错误的，会抛出一个异常（错误）。catch 会捕捉到这个错误，并显示一段自定义的错误消息：
     */
    function myFunction()
    {
        try
        {
            var x=document.getElementById("demo").value;
            if(x=="")    throw "empty";
            if(isNaN(x)) throw "not a number";
            if(x>10)     throw "too high";
            if(x<5)      throw "too low";
        }
        catch(err)
        {
            var y=document.getElementById("mess");
            y.innerHTML="Error: " + err + ".";
        }

    }

</script>

<h1>My First JavaScript</h1>
<p>Please input a number between 5 and 10:</p>
<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="mess"></p>
</body>

</html>